<?php

namespace App\Enums;

enum UserRole: string
{
    case SuperAdmin = 'super_admin';
    case HrManager = 'hr_manager';
    case HrAdmin = 'hr_admin';
    case Supervisor = 'supervisor';
    case Viewer = 'viewer';
    case Employee = 'employee';

    /**
     * @return array<int, string>
     */
    public function permissions(): array
    {
        return match ($this) {
            self::SuperAdmin => [
                'dashboard.view',
                'employees.view',
                'employees.manage',
                'positions.view',
                'positions.manage',
                'attendance.view',
                'attendance.manage',
                'attendance.settings',
                'leave.view',
                'leave.manage',
                'leave.settings',
                'overtime.view',
                'overtime.manage',
                'overtime.settings',
                'roster.view',
                'roster.manage',
                'roster.settings',
                'performance.view',
                'performance.manage',
                'performance.settings',
                'recruitment.view',
                'recruitment.manage',
                'recruitment.settings',
                'onboarding.view',
                'onboarding.manage',
                'training.view',
                'training.manage',
                'training.settings',
                'competency.view',
                'documents.view',
                'documents.manage',
                'documents.settings',
                'discipline.view',
                'discipline.manage',
                'discipline.settings',
                'separation.view',
                'separation.manage',
                'separation.clearance',
                'separation.settings',
                'claims.view',
                'claims.manage',
                'claims.settings',
                'payroll.view',
                'payroll.manage',
                'payroll.settings',
                'reports.view',
                'audit.view',
                'users.manage',
            ],
            self::HrManager => [
                'dashboard.view',
                'employees.view',
                'positions.view',
                'attendance.view',
                'leave.view',
                'leave.approve',
                'overtime.view',
                'overtime.approve',
                'roster.view',
                'roster.publish',
                'performance.view',
                'performance.finalize',
                'recruitment.view',
                'recruitment.approve',
                'onboarding.view',
                'onboarding.approve',
                'training.view',
                'training.approve',
                'competency.view',
                'documents.view',
                'documents.approve',
                'discipline.view',
                'discipline.approve',
                'separation.view',
                'separation.approve',
                'claims.view',
                'claims.approve',
                'payroll.view',
                'payroll.approve',
                'reports.view',
                'audit.view',
            ],
            self::HrAdmin => [
                'dashboard.view',
                'employees.view',
                'employees.manage',
                'positions.view',
                'positions.manage',
                'attendance.view',
                'attendance.manage',
                'leave.view',
                'leave.manage',
                'leave.settings',
                'overtime.view',
                'overtime.manage',
                'overtime.settings',
                'roster.view',
                'roster.manage',
                'roster.settings',
                'performance.view',
                'performance.manage',
                'performance.moderate',
                'performance.settings',
                'recruitment.view',
                'recruitment.manage',
                'recruitment.interview',
                'recruitment.settings',
                'onboarding.view',
                'onboarding.manage',
                'training.view',
                'training.manage',
                'training.settings',
                'competency.view',
                'competency.assess',
                'documents.view',
                'documents.manage',
                'documents.settings',
                'discipline.view',
                'discipline.manage',
                'discipline.investigate',
                'discipline.settings',
                'separation.view',
                'separation.manage',
                'separation.clearance',
                'separation.settings',
                'claims.view',
                'claims.manage',
                'claims.settings',
                'payroll.view',
                'payroll.manage',
                'payroll.settings',
                'reports.view',
                'audit.view',
            ],
            self::Supervisor => [
                'dashboard.view',
                'employees.view',
                'positions.view',
                'attendance.view',
                'leave.view',
                'leave.supervise',
                'overtime.view',
                'overtime.supervise',
                'roster.view',
                'roster.supervise',
                'performance.view',
                'performance.supervise',
                'recruitment.view',
                'recruitment.interview',
                'onboarding.view',
                'training.view',
                'training.supervise',
                'competency.view',
                'competency.assess',
                'documents.view',
                'discipline.view',
                'discipline.investigate',
                'separation.view',
                'separation.supervise',
                'separation.clearance',
                'claims.view',
                'claims.supervise',
            ],
            self::Viewer => [
                'dashboard.view',
                'employees.view',
                'positions.view',
                'attendance.view',
                'leave.view',
                'overtime.view',
                'roster.view',
                'recruitment.view',
                'training.view',
                'competency.view',
                'separation.view',
                'separation.clearance',
            ],
            self::Employee => [
                'dashboard.view',
                'employee.profile.view',
                'employee.profile.update',
                'leave.self',
                'leave.apply',
                'attendance.clock',
                'overtime.self',
                'overtime.apply',
                'roster.self',
                'roster.swap',
                'performance.self',
                'onboarding.self',
                'training.self',
                'training.apply',
                'competency.self',
                'documents.self',
                'discipline.self',
                'discipline.apply',
                'separation.self',
                'separation.apply',
                'claims.self',
                'claims.apply',
                'payslip.self',
            ],
        };
    }

    public function hasPermission(string $permission): bool
    {
        return in_array($permission, $this->permissions(), true);
    }

    public function label(): string
    {
        return match ($this) {
            self::SuperAdmin => 'Super Admin',
            self::HrManager => 'Pengurus HR',
            self::HrAdmin => 'HR Admin',
            self::Supervisor => 'Penyelia / Ketua Jabatan',
            self::Viewer => 'Viewer / Pemerhati',
            self::Employee => 'Employee',
        };
    }

    public function description(): string
    {
        return match ($this) {
            self::SuperAdmin => 'Akses teknikal penuh kepada semua modul, pengguna, role, konfigurasi, keselamatan dan Audit Trail tanpa kuasa kelulusan HR.',
            self::HrManager => 'Kuasa perniagaan HR tertinggi untuk kelulusan akhir, keputusan rasmi dan pemuktamadan tanpa mengurus pengguna atau konfigurasi teknikal.',
            self::HrAdmin => 'Memproses transaksi, menyediakan rekod, mengurus modul HR dan konfigurasi polisi tanpa kuasa kelulusan akhir.',
            self::Supervisor => 'Semak pengakhiran dan clearance yang ditugaskan, dokumen, kes siasatan, pengambilan, temu duga, onboarding, latihan, kompetensi, cuti, OT, tuntutan, pertukaran syif dan prestasi jabatan.',
            self::Viewer => 'Akses paparan operasi serta tugasan clearance yang ditugaskan tanpa kuasa perubahan atau kelulusan.',
            self::Employee => 'Akses profil, notis pengakhiran, clearance, dokumen, aduan sulit, onboarding, latihan, kompetensi, roster, prestasi, cuti, OT, tuntutan, kehadiran dan slip gaji sendiri.',
        };
    }

    public function priority(): int
    {
        return match ($this) {
            self::SuperAdmin => 500,
            self::HrManager => 400,
            self::HrAdmin => 300,
            self::Supervisor => 250,
            self::Viewer => 200,
            self::Employee => 100,
        };
    }
}
